package sqlc

import (
	"context"
	"testing"
	"time"

	"github.com/Ahdaaa/go-backend-mastery-module/tree/main/util"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/stretchr/testify/require"
)

func createRandomAccount(t *testing.T) Accounts {
	preBalance := util.RandomMoney()

	balance := pgtype.Numeric{}
	balance.Scan(preBalance)

	arg := CreateAccountParams{
		Owner:    util.RandomOwner(),
		Balance:  balance,
		Currency: util.RandomCurrency(),
	}

	account, err := testQueries.CreateAccount(context.Background(), arg)

	require.NoError(t, err)
	require.NotEmpty(t, account)

	// Equal will make sure that the pre-inserted values
	// are the same with the post-inserted
	require.Equal(t, arg.Owner, account.Owner)
	require.Equal(t, arg.Balance, account.Balance)
	require.Equal(t, arg.Currency, account.Currency)

	// Check the ID and CreatedAt is automatically
	// generated by postgres
	require.NotZero(t, account.ID)
	require.NotZero(t, account.CreatedAt)
	return account
}
func TestCreateAccount(t *testing.T) {
	createRandomAccount(t)
}

func TestGetAccount(t *testing.T) {
	account1 := createRandomAccount(t)
	account2, err := testQueries.GetAccount(context.Background(), account1.ID)

	require.NoError(t, err)
	require.NotEmpty(t, account2)

	require.Equal(t, account1.ID, account2.ID)
	require.Equal(t, account1.Owner, account2.Owner)
	require.Equal(t, account1.Balance, account2.Balance)
	require.Equal(t, account1.Currency, account2.Currency)
	require.WithinDuration(t, account1.CreatedAt.Time, account2.CreatedAt.Time, time.Second)

}

func TestUpdateAccount(t *testing.T) {
	account := createRandomAccount(t)

	preBalance := util.RandomMoney()
	balance := pgtype.Numeric{}
	balance.Scan(preBalance)

	arg := UpdateAccountParams{
		ID:      account.ID,
		Balance: balance,
	}

	account2, err := testQueries.UpdateAccount(context.Background(), arg)
	require.NoError(t, err)
	require.NotEmpty(t, account.Owner, account2.Owner)
	require.Equal(t, arg.Balance, account2.Balance)

	require.Equal(t, account.Currency, account2.Currency)
	require.WithinDuration(t, account.CreatedAt.Time, account2.CreatedAt.Time, time.Second)
}

func TestDeleteAccount(t *testing.T) {
	account := createRandomAccount(t)
	err := testQueries.DeleteAccount(context.Background(), account.ID)
	require.NoError(t, err)

	account2, err := testQueries.GetAccount(context.Background(), account.ID)
	require.Error(t, err)
	require.Equal(t, err, ErrRecordNotFound)
	require.Empty(t, account2)
}

func TestListAccounts(t *testing.T) {
	for i := 0; i < 10; i++ {
		createRandomAccount(t)
	}

	arg := ListAccountsParams{
		Limit:  5, // 5 max
		Offset: 5, // skip first 5 return next 5
	}

	accounts, err := testQueries.ListAccounts((context.Background()), arg)
	require.NoError(t, err)
	require.Len(t, accounts, 5)

	for _, account := range accounts { // for account in accounts
		require.NotEmpty(t, account)
	}

}
