// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        int64
	Owner     string
	Balance   pgtype.Numeric
	Currency  string
	CreatedAt pgtype.Timestamptz
}

type Entry struct {
	ID        int64
	AccountID int64
	// can be negative/positive
	Amount    pgtype.Numeric
	CreatedAt pgtype.Timestamptz
}

type Transfer struct {
	ID                int64
	SenderAccountID   int64
	ReceiverAccountID int64
	// must be positive
	Amount    pgtype.Numeric
	CreatedAt pgtype.Timestamptz
}
