// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Accounts struct {
	ID        int64              `json:"id"`
	Owner     string             `json:"owner"`
	Balance   pgtype.Numeric     `json:"balance"`
	Currency  string             `json:"currency"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Entries struct {
	ID        int64 `json:"id"`
	AccountID int64 `json:"account_id"`
	// can be negative/positive
	Amount    pgtype.Numeric     `json:"amount"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Transfers struct {
	ID                int64 `json:"id"`
	SenderAccountID   int64 `json:"sender_account_id"`
	ReceiverAccountID int64 `json:"receiver_account_id"`
	// must be positive
	Amount    pgtype.Numeric     `json:"amount"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
